package hiruvilla;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.*;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;
import sun.util.logging.PlatformLogger;

/**
 *
 * @author Dumindu
 */

public class HiruVilla_Suppliers extends javax.swing.JFrame {

    /**
     * Creates new form HiruVilla_Suppliers
     */
    
    Connection conn=null; 
    ResultSet rs=null;
    PreparedStatement pst=null;
    
     String s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13;
     
    public HiruVilla_Suppliers() {
        initComponents();
        conn=javaconnect.ConnecrDb();
        Fillcombo();
        Update_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Suppliers = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Delete_Button = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 760));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel9.setText("Supplier_ID");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(12, 213, 90, 19);

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel13.setText("Name");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(14, 258, 70, 19);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(22, 293, 46, 19);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(102, 213, 170, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(102, 253, 170, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(102, 293, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel4.setText("Enter productID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 123, 160, 20);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel7.setText("Tel");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(22, 356, 46, 19);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(102, 356, 170, 30);

        Table_Suppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_Suppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_SuppliersMouseClicked(evt);
            }
        });
        Table_Suppliers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Table_SuppliersKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Suppliers);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(66, 392, 767, 136);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setText("Insert");
        jButton1.setActionCommand("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(354, 196, 110, 30);

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton2.setLabel("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(354, 246, 110, 30);

        Delete_Button.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        Delete_Button.setLabel("Delete");
        Delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Delete_Button);
        Delete_Button.setBounds(354, 296, 110, 30);

        jButton4.setFont(new java.awt.Font("Tempus Sans ITC", 2, 14)); // NOI18N
        jButton4.setText("<<Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(354, 356, 110, 30);

        jComboBox1.setMaximumRowCount(1000);
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(222, 118, 160, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hiruvilla/Back_Supp.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1110, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        insert_data();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            String value1 = jTextField1.getText();
            String value2 = jTextField2.getText();
            String value3 = jTextField3.getText();
            String value4 = jTextField4.getText();

            String sql = "update suppliers set Supplier_ID = '"+value1+"', Sup_Name = '"+value2+"', Address ='"+value3+"', TP ='"+value4+"' where Supplier_ID = '"+value1+"'";
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Updated Sucsussfully!");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        Update_table();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_ButtonActionPerformed
        
        int p = JOptionPane.showConfirmDialog(null,"Do you really want to delete","Delete",JOptionPane.YES_NO_OPTION);
            if (p==0)
            {
             String sql = "delete from suppliers where Supplier_ID = ?";
             try
             {
                pst = conn.prepareStatement(sql);
                pst.setString(1, jTextField1.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null,"Deleted Successfully!");
             }

             catch(Exception ex){
                JOptionPane.showMessageDialog(null,ex);
             }
            Update_table();
            }
    }//GEN-LAST:event_Delete_ButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.hide();
         HiruVilla_DataEnter obj1=new HiruVilla_DataEnter();//when Back boten click disply Administrater form
        obj1.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed
 
    
    
    private void Table_SuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_SuppliersMouseClicked
        try{
            int row = Table_Suppliers.getSelectedRow();
            String Table_click = (Table_Suppliers.getModel().getValueAt(row,0).toString()); 
        
            String sql = "select * from suppliers where Supplier_ID = '"+Table_click+"'";
            pst = conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            if(rs.next()){
                
                String add1 = rs.getString("Supplier_ID");
                jTextField1.setText(add1);
                
                String add2 = rs.getString("Sup_Name");
                jTextField2.setText(add2);
                
                String add3 = rs.getString("Address");
                jTextField3.setText(add3);
               
                String add4 = rs.getString("TP");
                jTextField4.setText(add4);
            
            
            }
        
        
        
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null,e);
        
        
    }       
    }//GEN-LAST:event_Table_SuppliersMouseClicked

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        String tmp = (String)jComboBox1.getSelectedItem();
        String sql = "select*  from suppliers where Supplier_ID=?";

        try
        {   pst=conn.prepareStatement(sql);
            pst.setString(1,tmp);
            rs=pst.executeQuery();
            if (rs.next()){
                String add1=rs.getString("Supplier_ID");
                jTextField1.setText(add1);
                String add2=rs.getString("Sup_Name");
                jTextField2.setText(add2);
                String add3=rs.getString("Address");
                jTextField3.setText(add3);
                String add4=rs.getString("TP");
                jTextField4.setText(add3);
            }

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseEntered

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MousePressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void Table_SuppliersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_SuppliersKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_DOWN||evt.getKeyCode()==KeyEvent.VK_UP)
        {
               try
       {     
           int row =Table_Suppliers.getSelectedRow();
           String table_click =(Table_Suppliers.getModel().getValueAt(row,0).toString());
             String sql="select * from suppliers where Supplier_ID='"+table_click+"' ";
            pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
          if(rs.next()){
          String add1=rs.getString("Supplier_ID");
                jTextField1.setText(add1);
                String add2=rs.getString("Sup_Name");
                jTextField2.setText(add2);
                String add3=rs.getString("Address");
                jTextField3.setText(add3);
                String add4=rs.getString("TP");
                jTextField4.setText(add3);
        }
        }
    catch(Exception ex)
    {
       JOptionPane.showMessageDialog(null,ex);
    } 
    }
    }//GEN-LAST:event_Table_SuppliersKeyPressed

        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HiruVilla_Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HiruVilla_Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HiruVilla_Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HiruVilla_Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HiruVilla_Suppliers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete_Button;
    private javax.swing.JTable Table_Suppliers;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    
    private void Fillcombo(){
    try
       {
           
        String sql="select* from suppliers";
           
        pst=conn.prepareStatement(sql);
          rs=pst.executeQuery(sql);
          while(rs.next()){
                 String name = rs.getString("Supplier_ID");
                 jComboBox1.addItem(name);
               }
          }
       catch(Exception ex)
        {
         JOptionPane.showMessageDialog(null,ex);       
        }
    }
    
    
    private void   Update_table(){
        try
       {
           
        String sql="select *  from suppliers";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
          
                Table_Suppliers.setModel(DbUtils.resultSetToTableModel(rs));
          
          
           
          

       }
       catch(Exception ex)
        {
         JOptionPane.showMessageDialog(null,ex);       
        }
    }
    
    

private void insert_data(){
 try{


s1=jTextField1.getText();
s2=jTextField2.getText();
s3=jTextField3.getText(); 
s4=jTextField4.getText(); 

    
  Class.forName("com.mysql.jdbc.Driver");
                          Connection mycon = DriverManager.getConnection("jdbc:mysql://localhost:3306/hiruvilla","root","");
                          Statement mystmnt = mycon.createStatement();
                          String sqlcode="insert into Suppliers(Supplier_ID,Sup_Name,Address,TP)" + "values('"+s1+"','"+s2+"','"+s3+"','"+s4+"');";
                          mystmnt.executeUpdate(sqlcode);
 
 JOptionPane.showMessageDialog(null,"saved"); 

    
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(null,e); 
 }
        Update_table();
    clear_data();    



}
private void clear_data(){

    
 jTextField1.setText("  ");
jTextField2.setText(" ");
jTextField3.setText("  "); 


} 

}

