/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hiruvilla;
import java.awt.event.*;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;
import sun.util.logging.PlatformLogger;


//import net.ptotenanit.sql.DbUltilis;
/**
 *
 * @author kalpa
 */
public class HiruVilla_Custommers extends javax.swing.JFrame {
    
    Connection conn=null; 
    ResultSet rs=null;
    PreparedStatement pst=null;
    private String gender;
    
    
    
    String s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13;
   String tmp;
    /**
     * Creates new form HiruVilla_Customers
     */
    public HiruVilla_Custommers() {
        initComponents();
        conn=javaconnect.ConnecrDb();
        Fillcombo();
        Update_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox12 = new javax.swing.JComboBox();
        jComboBox9 = new javax.swing.JComboBox();
        jComboBox10 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(15);
        setMinimumSize(new java.awt.Dimension(1300, 750));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel2.setText("     Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 370, 73, 14);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel3.setText("Country");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 410, 50, 19);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(560, 210, 42, 19);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(560, 320, 46, 19);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel7.setText("TP Nummber");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(530, 350, 81, 19);

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel8.setText("Admitted Date");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(520, 410, 87, 19);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(110, 240, 170, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(110, 280, 170, 30);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(110, 320, 170, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(110, 360, 170, 30);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(110, 400, 170, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(110, 200, 170, 30);

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel10.setText("Discharged Date");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(510, 460, 120, 19);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel9.setText("Customer_ID");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 210, 90, 19);

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel11.setText("Agent ID");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 290, 80, 19);

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel12.setText("Date of Birth");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 450, 110, 20);

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel13.setText("PPN");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(70, 330, 70, 19);

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel14.setText("Status");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(560, 250, 50, 19);

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel15.setText("Pakage ID");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(40, 250, 100, 19);

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10);
        jTextField10.setBounds(620, 310, 170, 30);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(620, 350, 170, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(620, 210, 60, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(680, 210, 110, 23);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 0));
        jButton1.setText("Insert");
        jButton1.setActionCommand("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(24, 45, 73, 29);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 0));
        jButton2.setLabel("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 77, 81, 29);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 0, 0));
        jButton3.setLabel("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(22, 109, 76, 29);

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 0, 0));
        jButton5.setText("Insert");
        jButton5.setActionCommand("Save");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(24, 45, 73, 29);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(970, 220, 120, 180);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tempus Sans ITC", 2, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 102));
        jButton4.setText("<<Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(950, 460, 160, 30);

        jComboBox2.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Married", "Unmarrid", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(620, 250, 140, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(110, 460, 0, 2);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2001", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", " " }));
        jComboBox3.setSelectedIndex(45);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(620, 460, 90, 30);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(720, 460, 80, 30);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " ", " " }));
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(810, 460, 50, 30);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2001", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "", "" }));
        jComboBox6.setSelectedIndex(16);
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(110, 450, 90, 30);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox7);
        jComboBox7.setBounds(210, 450, 80, 30);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " ", " " }));
        getContentPane().add(jComboBox8);
        jComboBox8.setBounds(300, 450, 50, 30);

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " ", " " }));
        getContentPane().add(jComboBox12);
        jComboBox12.setBounds(810, 400, 50, 30);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2001", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", " " }));
        jComboBox9.setSelectedIndex(45);
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox9);
        jComboBox9.setBounds(620, 400, 90, 30);

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        jComboBox10.setSelectedIndex(5);
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox10);
        jComboBox10.setBounds(720, 400, 80, 30);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Table", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trajan Pro", 3, 18), new java.awt.Color(0, 51, 51))); // NOI18N
        jPanel3.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer_ID", "Package_ID", "Agent_ID", "Name", "Country", "DateOfBirth", "Gender", "Status", "Address", "PPN", "TP", "Admitted_Date", "Discharged_Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(20, 40, 1150, 130);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 530, 1200, 200);

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setMinimumSize(new java.awt.Dimension(1000, 1000));
        jPanel8.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Coustomer Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trajan Pro", 1, 18), new java.awt.Color(0, 51, 51))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentHidden(evt);
            }
        });
        jPanel2.setLayout(null);

        jComboBox1.setMaximumRowCount(1000);
        jComboBox1.setMinimumSize(new java.awt.Dimension(150, 20));
        jComboBox1.setPreferredSize(new java.awt.Dimension(150, 30));
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(480, 30, 150, 30);
        jComboBox1.getAccessibleContext().setAccessibleName("");

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel4.setText("Enter customer ID");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(330, 30, 125, 19);

        jPanel8.add(jPanel2);
        jPanel2.setBounds(20, 120, 870, 380);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hiruvilla/Back cust.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel8.add(jLabel1);
        jLabel1.setBounds(-230, -20, 1690, 1130);

        jLabel16.setText("jLabel16");
        jPanel8.add(jLabel16);
        jLabel16.setBounds(1090, 190, 40, 15);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(0, 0, 1530, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
           
       
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
       
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
   clear_data();  
        try
       {   clear_data();  
           int row =jTable1.getSelectedRow();
           String table_click =(jTable1.getModel().getValueAt(row,0).toString());
             String sql="select*  from customer where Customer_ID='"+table_click+"' ";
            pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
          if(rs.next()){
          String add1=rs.getString("Customer_ID");
          jTextField1.setText(add1);
          String add2=rs.getString("Package_ID");
          jTextField2.setText(add2);
          String add3=rs.getString("Agent_ID");
          jTextField3.setText(add3);
          String add4=rs.getString("PPN");
          jTextField4.setText(add4);
          String add5=rs.getString("Name");
          jTextField5.setText(add5);
          String add6=rs.getString("Country");
          jTextField6.setText(add6);
          //String add7=rs.getString("DateOfBirth");
          
          String add10=rs.getString("Address");
          jTextField10.setText(add10);
          String add11=rs.getString("TP");
          jTextField11.setText(add11);
          String add12=rs.getString("Admitted_Date");
          //jTextField12.setText(add12);
          String add13=rs.getString("Discharged_Date");
          //jTextField13.setText(add13);
          
          
          }
          
       
       }
    catch(Exception ex)
    {
       JOptionPane.showMessageDialog(null,ex);
    } 

    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
               String tmp= (String)jComboBox1.getSelectedItem();
              String sql="select*  from customer where Customer_ID=?";
           
        try
       {    pst=conn.prepareStatement(sql);
             pst.setString(1,tmp);
          rs=pst.executeQuery();
          if (rs.next()){
          String add1=rs.getString("Customer_ID");
          jTextField1.setText(add1);
          String add2=rs.getString("Package_ID");
          jTextField2.setText(add2);
          String add3=rs.getString("Agent_ID");
          jTextField3.setText(add3);
          String add4=rs.getString("PPN");
          jTextField4.setText(add4);
          String add5=rs.getString("Name");
          jTextField5.setText(add5);
          String add6=rs.getString("Country");
          jTextField6.setText(add6);
          String add7=rs.getString("DateOfBirth");
          
          String add10=rs.getString("Address");
          jTextField10.setText(add10);
          String add11=rs.getString("TP");
          jTextField11.setText(add11);
          String add12=rs.getString("Admitted_Date");
          //jTextField12.setText(add12);
          String add13=rs.getString("Discharged_Date");
          //jTextField13.setText(add13);
          
          }
          
          
           
       
       }catch(Exception ex){
       JOptionPane.showMessageDialog(null,ex);   
       }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
                gender="male";
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.hide();
        HiruVilla_DataEnter obj1=new HiruVilla_DataEnter();//when Back boten click disply Administrater form
        obj1.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
         gender="female";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox10ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_DOWN||evt.getKeyCode()==KeyEvent.VK_UP)
        {
               try
       {   clear_data();  
           int row =jTable1.getSelectedRow();
           String table_click =(jTable1.getModel().getValueAt(row,0).toString());
             String sql="select*  from customer where Customer_ID='"+table_click+"' ";
            pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
          if(rs.next()){
          String add1=rs.getString("Customer_ID");
          jTextField1.setText(add1);
          String add2=rs.getString("Package_ID");
          jTextField2.setText(add2);
          String add3=rs.getString("Agent_ID");
          jTextField3.setText(add3);
          String add4=rs.getString("PPN");
          jTextField4.setText(add4);
          String add5=rs.getString("Name");
          jTextField5.setText(add5);
          String add6=rs.getString("Country");
          jTextField6.setText(add6);
          //String add7=rs.getString("DateOfBirth");
          
          String add10=rs.getString("Address");
          jTextField10.setText(add10);
          String add11=rs.getString("TP");
          jTextField11.setText(add11);
          String add12=rs.getString("Admitted_Date");
          //jTextField12.setText(add12);
          String add13=rs.getString("Discharged_Date");
          //jTextField13.setText(add13);
          
          
          }
          
       
       }
    catch(Exception ex)
    {
       JOptionPane.showMessageDialog(null,ex);
    } 
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void jPanel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorAdded
       
    }//GEN-LAST:event_jPanel2AncestorAdded

    private void jPanel2ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentHidden
       
    }//GEN-LAST:event_jPanel2ComponentHidden

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tmp= (String)jComboBox1.getSelectedItem();
        //Conform_Form obj1=new  Conform_Form();
        //obj1.setVisible(true);

        //if ( obj1.setValue()){
            delete( tmp);
            //}

        //Conform_Form obj1=new Conform_Form();//when Back boten click disply Administrater form
        //obj1.setVisible(true);
        //Update_table();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        update_Data();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SwingUtilities.invokeLater(new Runnable(){
            public void run() {
                jButton1.setBackground(Color.red);
            }
        });
        insert_data();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HiruVilla_Custommers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HiruVilla_Custommers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HiruVilla_Custommers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HiruVilla_Custommers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HiruVilla_Custommers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

private void Fillcombo(){
try
       {
           
        String sql="select* from customer";
           
        pst=conn.prepareStatement(sql);
          rs=pst.executeQuery(sql);
          while(rs.next()){
                 String name = rs.getString("Customer_ID");
                 jComboBox1.addItem(name);
               }
          }
       catch(Exception ex)
        {
         JOptionPane.showMessageDialog(null,ex);       
        }
}
public void   Update_table(){
try
       {
           
        String sql="select*  from customer";
            pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
          
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
          
          
           
          

       }
       catch(Exception ex)
        {
         JOptionPane.showMessageDialog(null,ex);       
        }
}
public void update_Data() {
 try{
            String val0= jTextField1.getText();
            String val1= jTextField2.getText();
            String val2= jTextField3.getText();
            String val3= jTextField4.getText(); 
            String val4= jTextField5.getText();
            String val5= jTextField6.getText();
            String val6=jComboBox6.getSelectedItem().toString()+jComboBox7.getSelectedItem().toString()+jComboBox8.getSelectedItem().toString();
            String val7=gender;
            String val8=jComboBox2.getSelectedItem().toString();
            String val9=jTextField10.getText();
            String val10=jTextField11.getText();
            String val11=jComboBox9.getSelectedItem().toString()+jComboBox10.getSelectedItem().toString()+jComboBox12.getSelectedItem().toString();
            String val12=jComboBox3.getSelectedItem().toString()+jComboBox4.getSelectedItem().toString()+jComboBox5.getSelectedItem().toString();

              
       String sql="update customer set Agent_ID='"+val2 +"',PPN='"+val3 +"',Name='"+val4 +"',Country='"+val5 +"',Package_ID='"+val1 +"',DateOfBirth='"+val6+"',Gender='"+val7+"',Status='"+val8+"',Address='"+val9+"',Admitted_Date='"+val11+"',Discharged_Date='"+val12+"',TP='"+val10+"' where Customer_ID='"+val0+"'";
       pst=conn.prepareStatement(sql);
       pst.execute();
       JOptionPane.showMessageDialog(null,"Updated");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        Update_table();
}  
public void delete(String Customer_ID) {
        
              
        try {
            String sql = "DELETE FROM customer WHERE Customer_ID = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            Update_table();
            JOptionPane.showMessageDialog(null,"Deleted");
        
            // set the corresponding param
            //pst.setString(1,Customer_ID);
            // execute the delete statement
            pst.executeUpdate();
              Update_table();
 
        } catch (SQLException e) 
                {
            System.out.println(e.getMessage());
        }
   
  //Update_table();
    
}


private void insert_data(){
 try{

                                    
s1=jTextField1.getText();
s2=jTextField2.getText();
s3=jTextField3.getText(); 
s4=jTextField4.getText();
s5=jTextField5.getText();
s6=jTextField6.getText();
s7=jComboBox6.getSelectedItem().toString()+jComboBox7.getSelectedItem().toString()+jComboBox8.getSelectedItem().toString();
s8=gender;

s9=jComboBox2.getSelectedItem().toString();

s10=jTextField10.getText();
s11=jTextField11.getText();
s12=jComboBox9.getSelectedItem().toString()+jComboBox10.getSelectedItem().toString()+jComboBox12.getSelectedItem().toString();
s13=jComboBox3.getSelectedItem().toString()+jComboBox4.getSelectedItem().toString()+jComboBox5.getSelectedItem().toString();

    
  Class.forName("com.mysql.jdbc.Driver");
                          Connection mycon = DriverManager.getConnection("jdbc:mysql://localhost:3306/hiruvilla","root","");
                          Statement mystmnt = mycon.createStatement();
                          String sqlcode="insert into Customer(Customer_ID,Package_ID,Agent_ID,PPN,Name,Country,DateOfBirth,Gender,Status,Address,TP,Admitted_Date,Discharged_Date)" +
                                  "values('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5+"','"+s6+"','"+s7+"','"+s8+"','"+s9+"','"+s10+"','"+s11+"','"+s12+"','"+s13+"');";
                          mystmnt.executeUpdate(sqlcode);
                             
                            Update_table();
                          JOptionPane.showMessageDialog(null,"saved"); 

    
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(null,e); 
 }
        
    clear_data();    


}
private void clear_data(){

    
 jTextField1.setText("  ");
jTextField2.setText(" ");
jTextField3.setText("  "); 
jTextField4.setText("  ");
jTextField5.setText("  ");
jTextField6.setText("  ");


jTextField10.setText("  ");
jTextField11.setText("  ");

} 


}

