package hiruvilla;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.*;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;
import sun.util.logging.PlatformLogger;
import sun.util.logging.PlatformLogger;


/**
 *
 * @author Dumindu
 */

public class HiruVilla_Agents extends javax.swing.JFrame {

    /**
     * Creates new form HiruVilla_Suppliers
     */
    
    Connection conn=null; 
    ResultSet rs=null;
    PreparedStatement pst=null;
    
     String s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13;
     
    public HiruVilla_Agents() {
        initComponents();
      conn=javaconnect.ConnecrDb();
        Fillcombo();
        Update_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Agents = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Delete_Button = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1100, 792));
        setMinimumSize(new java.awt.Dimension(1000, 692));
        setPreferredSize(null);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 592));
        getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel9.setText("Agent_ID");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(75, 152, 90, 19);

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel13.setText("Name");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(77, 197, 70, 19);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel6.setText("Country");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(85, 232, 46, 19);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(165, 152, 170, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(165, 192, 170, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(165, 232, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel4.setText("Enter AgentID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(75, 78, 160, 20);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(85, 273, 46, 19);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(165, 268, 170, 30);

        Table_Agents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_Agents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_AgentsMouseClicked(evt);
            }
        });
        Table_Agents.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Table_AgentsKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Agents);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(66, 415, 767, 136);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setText("Insert");
        jButton1.setActionCommand("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(456, 156, 110, 30);

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton2.setLabel("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(456, 206, 110, 30);

        Delete_Button.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        Delete_Button.setLabel("Delete");
        Delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Delete_Button);
        Delete_Button.setBounds(456, 256, 110, 30);

        jButton4.setFont(new java.awt.Font("Tempus Sans ITC", 2, 14)); // NOI18N
        jButton4.setText("<<Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(456, 316, 110, 30);

        jComboBox1.setMaximumRowCount(1000);
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(247, 104, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel8.setText("Tel");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(85, 321, 46, 19);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(165, 316, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back agent.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-110, 0, 1100, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        insert_data();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            String value1 = jTextField1.getText();
            String value2 = jTextField2.getText();
            String value3 = jTextField3.getText();
            String value4 = jTextField4.getText();
            String value5 = jTextField5.getText();

            String sql = "update internantional_agent set Agent_ID = '"+value1+"', Name = '"+value2+"', Country ='"+value3+"', Address ='"+value4+"',TP ='"+value5+"' where Agent_ID = '"+value1+"'";
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Updated Sucsussfully!");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        Update_table();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_ButtonActionPerformed
        
        int p = JOptionPane.showConfirmDialog(null,"Do you really want to delete","Delete",JOptionPane.YES_NO_OPTION);
            if (p==0)
            {
             String sql = "delete from international_agent where Agent_ID = ?";
             try
             {
                pst = conn.prepareStatement(sql);
                pst.setString(1, jTextField1.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null,"Deleted Successfully!");
             }

             catch(Exception ex){
                JOptionPane.showMessageDialog(null,ex);
             }
            Update_table();
            }
    }//GEN-LAST:event_Delete_ButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.hide();
       HiruVilla_DataEnter obj1=new  HiruVilla_DataEnter();//when Back boten click disply Administrater form
        obj1.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed
 
    
    
    private void Table_AgentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_AgentsMouseClicked
        try{
            int row = Table_Agents.getSelectedRow();
            String Table_click = (Table_Agents.getModel().getValueAt(row,0).toString()); 
        
            String sql = "select * from internantional_agent where Agent_ID = '"+Table_click+"'";
            pst = conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            if(rs.next()){
                
                String add1 = rs.getString("Agent_ID");
                jTextField1.setText(add1);
                
                String add2 = rs.getString("Name");
                jTextField2.setText(add2);
                
                String add3 = rs.getString("Country");
                jTextField3.setText(add3);
               
                String add4 = rs.getString("Address");
                jTextField4.setText(add4);
                
                String add5 = rs.getString("TP");
                jTextField5.setText(add5);

                
            
            }
        
        
        
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null,e);
        
        
    }       
    }//GEN-LAST:event_Table_AgentsMouseClicked

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        String tmp = (String)jComboBox1.getSelectedItem();
        String sql = "select*  from internantional_agent where Agent_ID=?";

        try
        {   pst=conn.prepareStatement(sql);
            pst.setString(1,tmp);
            rs=pst.executeQuery();
            if (rs.next()){
                String add1=rs.getString("Agent_ID");
                jTextField1.setText(add1);
                String add2=rs.getString("Name");
                jTextField2.setText(add2);
                String add3=rs.getString("Country");
                jTextField3.setText(add3);
                String add4=rs.getString("Address");
                jTextField4.setText(add4);
                String add5=rs.getString("TP");
                jTextField5.setText(add5);
            
            
            }

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseEntered

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MousePressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void Table_AgentsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_AgentsKeyPressed
  if(evt.getKeyCode()==KeyEvent.VK_DOWN||evt.getKeyCode()==KeyEvent.VK_UP)
        {
               try
       {     
           int row =Table_Agents.getSelectedRow();
           String table_click =(Table_Agents.getModel().getValueAt(row,0).toString());
             String sql="select*  from internantional_agent where Agent_ID='"+table_click+"' ";
            pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
          if(rs.next()){
           String add1=rs.getString("Agent_ID");
                jTextField1.setText(add1);
                String add2=rs.getString("Name");
                jTextField2.setText(add2);
                String add3=rs.getString("Country");
                jTextField3.setText(add3);
                String add4=rs.getString("Address");
                jTextField4.setText(add4);
                String add5=rs.getString("TP");
                jTextField5.setText(add5);
        }
        }
    catch(Exception ex)
    {
       JOptionPane.showMessageDialog(null,ex);
    } 
    }        // TODO add your handling code here:
    }//GEN-LAST:event_Table_AgentsKeyPressed

        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HiruVilla_Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HiruVilla_Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HiruVilla_Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HiruVilla_Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HiruVilla_Agents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete_Button;
    private javax.swing.JTable Table_Agents;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    
    private void Fillcombo(){
    try
       {
           
        String sql="select* from internantional_agent";
           
        pst=conn.prepareStatement(sql);
          rs=pst.executeQuery(sql);
          while(rs.next()){
                 String name = rs.getString("Agent_ID");
                 jComboBox1.addItem(name);
               }
          }
       catch(Exception ex)
        {
         JOptionPane.showMessageDialog(null,ex);       
        }
    }
    
    
    private void   Update_table(){
        try
       {
           
        String sql="select *  from internantional_agent";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
          
                Table_Agents.setModel(DbUtils.resultSetToTableModel(rs));
          
          
           
          

       }
       catch(Exception ex)
        {
         JOptionPane.showMessageDialog(null,ex);       
        }
    }
    
    

private void insert_data(){
 try{


s1=jTextField1.getText();
s2=jTextField2.getText();
s3=jTextField3.getText(); 
s4=jTextField4.getText(); 
s5=jTextField5.getText(); 

    
  Class.forName("com.mysql.jdbc.Driver");
                          Connection mycon = DriverManager.getConnection("jdbc:mysql://localhost:3306/hiruvilla","root","");
                          Statement mystmnt = mycon.createStatement();
                          String sqlcode="insert into internantional_agent(Agent_ID,Name,Country,Address,TP)" + "values('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5+"');";
                          mystmnt.executeUpdate(sqlcode);
 
 JOptionPane.showMessageDialog(null,"Record added Succsusfully!"); 

    
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(null,e); 
 }
        Update_table();
    clear_data();    



}
private void clear_data(){

    
 jTextField1.setText("  ");
jTextField2.setText(" ");
jTextField3.setText("  "); 


} 

}

